CREATE TABLE log(
  `id` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `message` TEXT,
  `level` TINYTEXT,
  `logger` TINYTEXT,
  `log_time` TIMESTAMP
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;;